In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('Mumbai_Home.csv')

In [3]:
df.head()

Unnamed: 0    Price  Area  Location  No. of Bedrooms  New/Resale  \
0           0  4850000   720  Kharghar                1           0   
1           1  4500000   600  Kharghar                1           0   
2           2  6700000   650  Kharghar                1           0   
3           3  4500000   650  Kharghar                1           0   
4           4  5000000   665  Kharghar                1           0   

   Gymnasium  Lift Available  Car Parking  Maintenance Staff  24x7 Security  \
0          0               1            1                  1              1   
1          1               1            1                  1              1   
2          1               1            1                  1              1   
3          0               1            1                  1              1   
4          0               1            1                  1              1   

   Children's Play Area  Clubhouse  Intercom  Landscaped Gardens  \
0                     0          0         0                   0   
1                     0          1         0                   0   
2                     1          1         1                   0   
3                     0          0         1                   1   
4                     0          0         1                   1   

   Indoor Games  Gas Connection  Jogging Track  Swimming Pool  
0             0               0              0              0  
1             0               0              1              1  
2             0               0              1              1  
3             0               0              0              0  
4             0               0              0              0

In [4]:
df.isnull().sum()

Unnamed: 0              0
Price                   0
Area                    0
Location                0
No. of Bedrooms         0
New/Resale              0
Gymnasium               0
Lift Available          0
Car Parking             0
Maintenance Staff       0
24x7 Security           0
Children's Play Area    0
Clubhouse               0
Intercom                0
Landscaped Gardens      0
Indoor Games            0
Gas Connection          0
Jogging Track           0
Swimming Pool           0
dtype: int64

# Load iris dataset

In [5]:
from sklearn.datasets import load_iris
data=load_iris()
X, y = data.data, data.target

# train_test_split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

# Standarization

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
X_train_standardize = scaler.transform(X_train)
X_test_standardize = scaler.transform(X_test)


# Normalization

In [7]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer().fit(X_train)
X_train_normalized = scaler.transform(X_train)
X_test_normalized = scaler.transform(X_test)

# Binarization

In [8]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=1.0).fit(X)
X_binarized = binarizer.transform(X)

# Encoding Non-Numeric Data

In [9]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Handling Missing Values

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'mean')
X_imputed = imputer.fit_transform(X)

# Creating Polynomial Features

In [11]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)

# Bulding Machine Lerning Models

### Supervised Learning model - It is involve training model on label data, where the target variable is known

# 1) Linear Regression - Used to predict continuous valuess by fitting a linear relationship between input features and target variables.


In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 2) Support Vector Machine (SVM) - Create a decision boundary (hyperplane) to separate data into different classes

In [13]:
from sklearn.svm import SVC
model = SVC(kernel= 'linear')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# 3) Naive Bayes - A fast algorithm based on Bayes'theorem, often used for text classifiction.

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

# 4) K-Nearest Neighbors - Classifies points based on the majority class of their nearest neighbors

In [15]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Unsupervised Learning Algorithms

# 1) PCA - Reduces high-dimensional data into fewer dimension while preserving variance.

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_pca = pca.fit_transform(X_train)

# 2) K-Means - Groups similar data points into cluster based on their features.

In [17]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X_train)
y_pred = kmeans.predict(X_test)

# Evaluation Model Performance

## Matrics for classification Models

# 1) Accuracy Score - Measures the proportion of correctly predicted labels

In [18]:
from sklearn.metrics import accuracy_score
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.36666666666666664


# 2) Classification Report (Precision, Recall, F1) - Provides detailed metrics for classification tasks

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00         9
           2       0.85      1.00      0.92        11

    accuracy                           0.37        30
   macro avg       0.28      0.33      0.31        30
weighted avg       0.31      0.37      0.34        30



# 3) Confusion Matrix Insights - Show the counts of true positive, true negatives, false positives , and false negatives

In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 0 10  0]
 [ 7  0  2]
 [ 0  0 11]]


### Metrics for Regression Models

# Mean Absolute Error (MAE) - Measures the averages absolute difference between predicted and actual values. 

In [21]:
from sklearn.metrics import mean_absolute_error
print("MAE : ",mean_absolute_error(y_test, y_pred))

MAE :  0.6333333333333333


# Mean Squared Error - Measures the averages square diffrence between predicted and actual values

In [22]:
from sklearn.metrics import mean_squared_error
print("MSE",mean_squared_error(y_test,y_pred))

MSE 0.6333333333333333


# R² Score - Indicate how well the model explains the variance in the target variable

In [23]:
from sklearn.metrics import r2_score
print("R² Score : ",r2_score(y_test,y_pred))

R² Score :  0.09379968203497613


# Metrics for Clustering 

# 1) Adjusted Rand Index - Evaluate the similarity between two clustering by considering all pairs of points

In [24]:
from sklearn.metrics import adjusted_rand_score
print("ARI:", adjusted_rand_score(y_test,y_pred))

ARI: 0.8104850421144351


# 2) Homogeneity - Check if clusters contain only data points that belong to a single class 

In [25]:
from sklearn.metrics import homogeneity_score
print("Homogeneity : ", homogeneity_score(y_test, y_pred))

Homogeneity :  0.8301428848702208


# 3) V-Measure - Measures the balance between homogeneity and completeness in clustering results. 

In [26]:
from sklearn.metrics import v_measure_score
print("V-Measure : ",v_measure_score(y_test,y_pred))

V-Measure :  0.8405524341147055


## Optimizing Models

# 1) Exhaustive Search with GridSearchCV - Test all combinations of hyperparameters to find the best set

In [27]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1, 1, 10], 'kernel' : ['linear', 'rbf']}
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid.fit(X_train, y_train)
print("Best Parameters : ", grid.best_params_)

Best Parameters :  {'C': 1, 'kernel': 'linear'}


# 2) Randomize Search for Hyperparameters - Randomly samples hyperparameters for a faster search

In [28]:
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(SVC(), param_distributions={'C':[0.1,1,10],'kernel':['linear','rbf']},n_iter=10)
random.fit(X_train, y_train)

C:\Users\xmrmo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


RandomizedSearchCV(estimator=SVC(),
                   param_distributions={'C': [0.1, 1, 10],
                                        'kernel': ['linear', 'rbf']})

# Practise ScikitLearn

In [8]:
df.head()

Unnamed: 0    Price  Area  Location  No. of Bedrooms  New/Resale  \
0           0  4850000   720  Kharghar                1           0   
1           1  4500000   600  Kharghar                1           0   
2           2  6700000   650  Kharghar                1           0   
3           3  4500000   650  Kharghar                1           0   
4           4  5000000   665  Kharghar                1           0   

   Gymnasium  Lift Available  Car Parking  Maintenance Staff  24x7 Security  \
0          0               1            1                  1              1   
1          1               1            1                  1              1   
2          1               1            1                  1              1   
3          0               1            1                  1              1   
4          0               1            1                  1              1   

   Children's Play Area  Clubhouse  Intercom  Landscaped Gardens  \
0                     0          0         0                   0   
1                     0          1         0                   0   
2                     1          1         1                   0   
3                     0          0         1                   1   
4                     0          0         1                   1   

   Indoor Games  Gas Connection  Jogging Track  Swimming Pool  
0             0               0              0              0  
1             0               0              1              1  
2             0               0              1              1  
3             0               0              0              0  
4             0               0              0              0

In [9]:
print('Null Check : ',df.isnull().sum())
print('Describe : ',df.describe())
print('Info : ',df.info())

Null Check :  Unnamed: 0              0
Price                   0
Area                    0
Location                0
No. of Bedrooms         0
New/Resale              0
Gymnasium               0
Lift Available          0
Car Parking             0
Maintenance Staff       0
24x7 Security           0
Children's Play Area    0
Clubhouse               0
Intercom                0
Landscaped Gardens      0
Indoor Games            0
Gas Connection          0
Jogging Track           0
Swimming Pool           0
dtype: int64
Describe :          Unnamed: 0         Price         Area  No. of Bedrooms   New/Resale  \
count  6347.000000  6.347000e+03  6347.000000      6347.000000  6347.000000   
mean   3173.000000  1.515401e+07  1004.327084         1.910036     0.341736   
std    1832.365411  2.015943e+07   556.375703         0.863304     0.474329   
min       0.000000  2.000000e+06   200.000000         1.000000     0.000000   
25%    1586.500000  5.300000e+06   650.000000         1.000000     0.000

In [10]:
df = pd.get_dummies(df, drop_first=True)

In [11]:
X=df.drop("Price", axis=1)
y=df["Price"]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Decision Tree Regressor 

In [16]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

model = DecisionTreeRegressor(max_depth=3)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("MSE : ",y_test,y_pred)

MSE :  730      5500000
5642     5742000
5263     8900000
4525     2600000
217     13500000
          ...   
2187     5600000
2389    11500000
2893     2399000
1128    30500000
5013    37600000
Name: Price, Length: 1270, dtype: int64 [ 5876494.30481862  5876494.30481862  5876494.30481862 ...
  5876494.30481862 49647916.65625    25571810.10864979]


# Random Forest 

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print("Accuracy : ",accuracy_score(y_test,y_pred))

Accuracy :  0.06929133858267716


# Linear Regression 

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

model = LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("Mean Absolute Error : ",mean_absolute_error(y_test,y_pred))

Mean Absolute Error :  5756335.799191631


# SVM - Support Vector Machine 

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

model = SVC(kernel="linear")
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print("SVM Accuracy : ", accuracy_score(y_test, y_pred))

# K-Mean

In [ ]:
# from sklearn.cluster import KMeans

# model = KMeans(n_clusters=3,random_state=42)
# model.fit(X)

# cluster = model.predict(X)

# df["Cluster"]=cluster

# df.head()

In [ ]:
# import joblib
# joblib.dumb(model,"House_pred.pkl")

In [ ]:
# model = joblib.load("House_pred.pkl")
# new_data=[[]]
# prediction=model.predict(new_data)
# print("Pridicted price of house is : ",prediction)