In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Array fundamentals

In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3],[4,5,6]])

In [5]:
a.shape

(2, 3)

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a[1]

array([4, 5, 6])

In [8]:
a[0]

array([1, 2, 3])

In [9]:
a[0]=5

In [10]:
a

array([[5, 5, 5],
       [4, 5, 6]])

In [11]:
b=np.array([1,2,3,4,5,6,7,8,9])

In [12]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[5]

np.int64(6)

In [14]:
b[4]=4

In [15]:
b

array([1, 2, 3, 4, 4, 6, 7, 8, 9])

In [16]:
b[:5]

array([1, 2, 3, 4, 4])

In [17]:
b[5:]

array([6, 7, 8, 9])

In [18]:
b

array([1, 2, 3, 4, 4, 6, 7, 8, 9])

In [19]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c[1, 1] #location of 5

np.int64(5)

In [22]:
# Array attributes

In [23]:
c.ndim

2

In [24]:
b.ndim

1

In [25]:
c.shape

(3, 3)

In [26]:
len(c.shape)

2

In [27]:
len(c.shape)==c.ndim

True

In [28]:
c.size

9

In [29]:
import math
math.prod(c.shape)

9

In [30]:
c.size==math.prod(c.shape)

True

In [31]:
c.dtype

dtype('int64')

In [32]:
# How to create a basic array

In [33]:
np.zeros(2)

array([0., 0.])

In [34]:
np.ones(2)

array([1., 1.])

In [35]:
np.empty(3)

array([ 1.24922479e-311,  0.00000000e+000, -3.96236456e-133])

In [36]:
np.arange(2,22,2) # start with 2 and end with before 22 with diffrence 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [37]:
np.linspace(0,10,num=8) # start with 0 and end with 10 with split equaly num 8

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [38]:
x = np.ones(2, dtype=np.int64)

In [39]:
x

array([1, 1])

In [40]:
# Adding, removing, and sorting elements

In [41]:
arr = np.array([5,4,9,7,3,3,4,8,1,2,3,89,7,6,12])

In [42]:
np.sort(arr)

array([ 1,  2,  3,  3,  3,  4,  4,  5,  6,  7,  7,  8,  9, 12, 89])

In [43]:
brr=np.array([7,8,4,56,98,756,4,23,187,69,98])

In [44]:
con=np.concatenate((arr,brr))

In [45]:
con

array([  5,   4,   9,   7,   3,   3,   4,   8,   1,   2,   3,  89,   7,
         6,  12,   7,   8,   4,  56,  98, 756,   4,  23, 187,  69,  98])

In [46]:
np.sort(con)

array([  1,   2,   3,   3,   3,   4,   4,   4,   4,   5,   6,   7,   7,
         7,   8,   8,   9,  12,  23,  56,  69,  89,  98,  98, 187, 756])

In [47]:
x=np.array([[4,5,6],[8,5,2]])
y=np.array([[6,5,4],[9,5,1]])
np.concatenate((x,y), axis=0)

array([[4, 5, 6],
       [8, 5, 2],
       [6, 5, 4],
       [9, 5, 1]])

In [48]:
array_example=np.array([[[0,1,2,3],[4,5,6,8]],[[0,1,2,3],[4,5,6,8]],[[0,1,2,3],[4,5,6,8]]])

In [49]:
array_example.ndim

3

In [50]:
array_example.size

24

In [51]:
array_example.shape

(3, 2, 4)

In [52]:
# Can you reshape an array?

In [53]:
d= np.arange(6)

In [54]:
d

array([0, 1, 2, 3, 4, 5])

In [55]:
e=d.reshape(3,2)

In [56]:
e

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
np.reshape(d, shape=(1,6), order='C') # order: C means to read/write the elements using C-like index order

array([[0, 1, 2, 3, 4, 5]])

In [58]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [59]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [60]:
a2_row = a[np.newaxis,:] # Row

In [61]:
a2_row.shape

(1, 6)

In [62]:
a3_col=a[:,np.newaxis] # Coloumn

In [63]:
a3_col.shape

(6, 1)

In [94]:
b=np.arange(0,10,6)

In [95]:
b

array([0, 6])

In [96]:
 a= np.ones((3, 3), dtype=np.int64)

In [97]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [123]:
c=np.linspace(1,9,9)

In [124]:
c

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [110]:
d=np.eye(3)

In [112]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
c

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [126]:
f=c.reshape(3,3)

In [128]:
f

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [129]:
g=np.arange(10)

In [130]:
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
h=g.reshape(5,2)

In [141]:
h

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [142]:
h[2]

array([4, 5])

In [143]:
i=np.delete(h,2,axis=0)

In [144]:
i

array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

In [145]:
h

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [148]:
print("Mean",np.mean(h))
print("Median",np.median(h))
print("std",np.std(h))
print("sum",np.sum(h))
print("Min",np.min(h))
print("Max",np.max(h))

Mean 4.5
Median 4.5
std 2.8722813232690143
sum 45
Min 0
Max 9


In [149]:
j=np.arange(10)

In [150]:
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
print(j[3])
print(j[-1])
print(j[3:5])

3
9
[3 4]


In [166]:
k=j[::-1]

In [169]:
k=np.flip(j)

In [170]:
k

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [173]:
print(j+k)
print(j-k)
print(j*k)
print(j/k)

[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[0.         0.125      0.28571429 0.5        0.8        1.25
 2.         3.5        8.                inf]


C:\Users\xmrmo\AppData\Local\Temp\ipykernel_9204\27825254.py:4: RuntimeWarning: divide by zero encountered in divide
  print(j/k)


In [180]:
l=np.arange(6)

In [183]:
n=m[::-1]

In [181]:
m=l.reshape(3,2)

In [182]:
m

array([[0, 1],
       [2, 3],
       [4, 5]])

In [184]:
n

array([[4, 5],
       [2, 3],
       [0, 1]])

In [187]:
print(m+n)
print(m-n)
print(m*n)
print(m/n)

[[4 6]
 [4 6]
 [4 6]]
[[-4 -4]
 [ 0  0]
 [ 4  4]]
[[0 5]
 [4 9]
 [0 5]]
[[0.  0.2]
 [1.  1. ]
 [inf 5. ]]


C:\Users\xmrmo\AppData\Local\Temp\ipykernel_9204\558966692.py:4: RuntimeWarning: divide by zero encountered in divide
  print(m/n)


In [5]:
# empty array
import numpy as np
empty_arry=np.empty((3,2))

In [6]:
empty_arry

array([[2.31297541e-312, 2.46151512e-312],
       [2.01589600e-312, 2.41907520e-312],
       [2.56761491e-312, 1.05699581e-307]])

In [8]:
# full array
import numpy as np
full_arry=np.full((3,3),69)

In [9]:
full_arry

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [10]:
# append a NumPy array to an empty array
import numpy as np
arr=np.array([])
arr=np.append(arr,np.array(['A','B','C']))
arr=np.append(arr,np.array(['D','E','F']))
arr=np.append(arr,np.array(['G','H','I']))

In [11]:
arr

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='<U32')

In [17]:
arr1=arr.reshape((3,3))

In [18]:
arr1

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U32')

In [28]:
arr2=np.array([])
arr2=np.hstack((arr2,np.array(['M','O','H','T'])))
#print(arr2)
arr2=np.vstack((arr2,np.array(['F','A','T','G'])))
arr2=np.vstack((arr2,np.array(['R','I','C','H'])))
print(arr2)

[['M' 'O' 'H' 'T']
 ['F' 'A' 'T' 'G']
 ['R' 'I' 'C' 'H']]


In [30]:
# Check whether a Numpy array contains a specified row
(['M','O','H','I','T'] in arr2.tolist())

False

In [35]:
# Remove rows in Numpy array that contains non-numeric values

nan=np.array([[10.5,45.6,78.6]
             ,[72.5,np.nan,np.nan]])
print("Before Remove",nan)
rem_nan=nan[~np.isnan(nan).any(axis=1)]
print("After Remove",rem_nan)

Before Remove [[10.5 45.6 78.6]
 [72.5  nan  nan]]
After Remove [[10.5 45.6 78.6]]


In [15]:
import numpy as np
a=np.arange(9)

In [16]:
a = a.reshape(3,3)

In [17]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
a.argmin(axis=1)

array([0, 0, 0])